package shein

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type Store struct {
	pool *pgxpool.Pool
}

type ShopSummary struct {
	ShopKey     string    `json:"shop_key"`
	APIBaseURL  string    `json:"api_base_url"`
	OpenKeyHint string    `json:"open_key_hint"`
	Credentials bool      `json:"credentials_ready"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type OperationRecord struct {
	Status       string
	RequestHash  string
	Response     map[string]any
	ErrorMessage string
}

func NewStore(ctx context.Context, databaseURL string) (*Store, error) {
	if strings.TrimSpace(databaseURL) == "" {
		return nil, errors.New("SHEIN_DATABASE_URL is required")
	}
	pool, err := pgxpool.New(ctx, databaseURL)
	if err != nil {
		return nil, fmt.Errorf("open SHEIN database: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("ping SHEIN database: %w", err)
	}
	return &Store{pool: pool}, nil
}

func (s *Store) Close() {
	s.pool.Close()
}

func (s *Store) Migrate(ctx context.Context) error {
	_, err := s.pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS shein_go_api_operations (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			shop_key text NOT NULL,
			operation text NOT NULL,
			idempotency_key text NOT NULL,
			request_hash text NOT NULL,
			status text NOT NULL DEFAULT 'pending',
			response jsonb,
			error_message text,
			created_at timestamptz NOT NULL DEFAULT now(),
			completed_at timestamptz,
			UNIQUE (shop_key, operation, idempotency_key)
		);
		CREATE INDEX IF NOT EXISTS idx_shein_go_api_operations_created
			ON shein_go_api_operations (shop_key, created_at DESC);
	`)
	if err != nil {
		return fmt.Errorf("migrate SHEIN Go tables: %w", err)
	}
	return nil
}

func (s *Store) Credentials(ctx context.Context, shopKey string) (Credentials, error) {
	shopKey = strings.TrimSpace(shopKey)
	if shopKey == "" {
		shopKey = "default"
	}
	var credentials Credentials
	err := s.pool.QueryRow(ctx, `
		SELECT shop_key, open_key_id, secret_key, base_url
		FROM shein_shops
		WHERE shop_key = $1
	`, shopKey).Scan(&credentials.ShopKey, &credentials.OpenKeyID, &credentials.SecretKey, &credentials.BaseURL)
	if errors.Is(err, pgx.ErrNoRows) {
		return Credentials{}, fmt.Errorf("SHEIN shop %q is not configured", shopKey)
	}
	if err != nil {
		return Credentials{}, fmt.Errorf("load SHEIN shop credentials: %w", err)
	}
	if credentials.OpenKeyID == "" || credentials.SecretKey == "" {
		return Credentials{}, fmt.Errorf("SHEIN shop %q credentials are incomplete", shopKey)
	}
	return credentials, nil
}

func (s *Store) ListShops(ctx context.Context) ([]ShopSummary, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT shop_key, base_url, open_key_id, updated_at
		FROM shein_shops
		ORDER BY shop_key
	`)
	if err != nil {
		return nil, fmt.Errorf("list SHEIN shops: %w", err)
	}
	defer rows.Close()
	shops := make([]ShopSummary, 0)
	for rows.Next() {
		var shop ShopSummary
		var openKeyID string
		if err := rows.Scan(&shop.ShopKey, &shop.APIBaseURL, &openKeyID, &shop.UpdatedAt); err != nil {
			return nil, fmt.Errorf("scan SHEIN shop: %w", err)
		}
		shop.Credentials = openKeyID != ""
		shop.OpenKeyHint = credentialHint(openKeyID)
		shops = append(shops, shop)
	}
	return shops, rows.Err()
}

func credentialHint(value string) string {
	if len(value) <= 8 {
		return strings.Repeat("*", len(value))
	}
	return value[:4] + "..." + value[len(value)-4:]
}

func (s *Store) ReserveOperation(ctx context.Context, shopKey, operation, idempotencyKey, requestHash string) (OperationRecord, bool, error) {
	if len(idempotencyKey) < 8 || len(idempotencyKey) > 200 {
		return OperationRecord{}, false, errors.New("Idempotency-Key must contain between 8 and 200 characters")
	}
	tag, err := s.pool.Exec(ctx, `
		INSERT INTO shein_go_api_operations (shop_key, operation, idempotency_key, request_hash)
		VALUES ($1, $2, $3, $4)
		ON CONFLICT DO NOTHING
	`, shopKey, operation, idempotencyKey, requestHash)
	if err != nil {
		return OperationRecord{}, false, fmt.Errorf("reserve SHEIN operation: %w", err)
	}
	if tag.RowsAffected() == 1 {
		return OperationRecord{Status: "pending", RequestHash: requestHash}, true, nil
	}
	var record OperationRecord
	var responseJSON []byte
	err = s.pool.QueryRow(ctx, `
		SELECT status, request_hash, COALESCE(response, '{}'::jsonb), COALESCE(error_message, '')
		FROM shein_go_api_operations
		WHERE shop_key = $1 AND operation = $2 AND idempotency_key = $3
	`, shopKey, operation, idempotencyKey).Scan(&record.Status, &record.RequestHash, &responseJSON, &record.ErrorMessage)
	if err != nil {
		return OperationRecord{}, false, fmt.Errorf("load reserved SHEIN operation: %w", err)
	}
	if record.RequestHash != requestHash {
		return OperationRecord{}, false, errors.New("Idempotency-Key was already used with a different request")
	}
	if len(responseJSON) > 0 {
		_ = json.Unmarshal(responseJSON, &record.Response)
	}
	return record, false, nil
}

func (s *Store) CompleteOperation(ctx context.Context, shopKey, operation, idempotencyKey string, response map[string]any) error {
	encoded, err := json.Marshal(response)
	if err != nil {
		return fmt.Errorf("encode SHEIN operation response: %w", err)
	}
	_, err = s.pool.Exec(ctx, `
		UPDATE shein_go_api_operations
		SET status = 'completed', response = $4::jsonb, completed_at = now(), error_message = NULL
		WHERE shop_key = $1 AND operation = $2 AND idempotency_key = $3
	`, shopKey, operation, idempotencyKey, encoded)
	if err != nil {
		return fmt.Errorf("complete SHEIN operation: %w", err)
	}
	return nil
}

func (s *Store) FailOperation(ctx context.Context, shopKey, operation, idempotencyKey, message string) error {
	if len(message) > 1000 {
		message = message[:1000]
	}
	_, err := s.pool.Exec(ctx, `
		UPDATE shein_go_api_operations
		SET status = 'failed', completed_at = now(), error_message = $4
		WHERE shop_key = $1 AND operation = $2 AND idempotency_key = $3
	`, shopKey, operation, idempotencyKey, message)
	if err != nil {
		return fmt.Errorf("fail SHEIN operation: %w", err)
	}
	return nil
}
