CREATE TABLE IF NOT EXISTS xlwms_warehouses (
    wh_code text PRIMARY KEY,
    warehouse_name text,
    api_base_url text NOT NULL,
    app_key_ciphertext text NOT NULL,
    app_secret_ciphertext text NOT NULL,
    app_key_hint text NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    disabled_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_xlwms_warehouses_active
    ON xlwms_warehouses (wh_code) WHERE is_active;

CREATE TABLE IF NOT EXISTS xlwms_funds_flows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key text NOT NULL UNIQUE,
    wh_code text NOT NULL REFERENCES xlwms_warehouses(wh_code),
    order_no text,
    platform_order_no text,
    cost_total numeric,
    currency_code text,
    cost_status integer,
    module_type integer,
    cost_time timestamp without time zone,
    bill_status integer,
    relate_bill_no text,
    raw_payload jsonb NOT NULL,
    snapshot_token uuid,
    detail_sync_status text NOT NULL DEFAULT 'pending',
    detail_attempts integer NOT NULL DEFAULT 0,
    detail_last_attempt_at timestamptz,
    detail_error_code text,
    detail_error_message text,
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE xlwms_funds_flows
    ADD COLUMN IF NOT EXISTS snapshot_token uuid,
    ADD COLUMN IF NOT EXISTS detail_sync_status text NOT NULL DEFAULT 'pending',
    ADD COLUMN IF NOT EXISTS detail_attempts integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS detail_last_attempt_at timestamptz,
    ADD COLUMN IF NOT EXISTS detail_error_code text,
    ADD COLUMN IF NOT EXISTS detail_error_message text;

CREATE INDEX IF NOT EXISTS idx_xlwms_funds_flows_order
    ON xlwms_funds_flows (wh_code, order_no);
CREATE INDEX IF NOT EXISTS idx_xlwms_funds_flows_platform_order
    ON xlwms_funds_flows (wh_code, platform_order_no);
CREATE INDEX IF NOT EXISTS idx_xlwms_funds_flows_cost_time
    ON xlwms_funds_flows (wh_code, cost_time DESC);
CREATE INDEX IF NOT EXISTS idx_xlwms_funds_flows_module_status
    ON xlwms_funds_flows (wh_code, module_type, cost_status, bill_status);

CREATE TABLE IF NOT EXISTS xlwms_cost_details (
    wh_code text NOT NULL REFERENCES xlwms_warehouses(wh_code),
    cost_no text NOT NULL,
    query_order_no text NOT NULL,
    query_order_type integer NOT NULL,
    cost_total numeric,
    bill_status integer,
    module_type integer,
    currency_code text,
    cost_status integer,
    create_time timestamp without time zone,
    platform_order_no text,
    relate_bill_no text,
    raw_payload jsonb NOT NULL,
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_fetched_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (wh_code, cost_no),
    CHECK (query_order_type IN (1, 2))
);

CREATE INDEX IF NOT EXISTS idx_xlwms_cost_details_query_order
    ON xlwms_cost_details (wh_code, query_order_no, query_order_type);
CREATE INDEX IF NOT EXISTS idx_xlwms_cost_details_platform_order
    ON xlwms_cost_details (wh_code, platform_order_no);

CREATE TABLE IF NOT EXISTS xlwms_cost_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wh_code text NOT NULL,
    cost_no text NOT NULL,
    item_index integer NOT NULL,
    bill_item_name text,
    bill_item_total numeric,
    charge_time timestamp without time zone,
    raw_payload jsonb NOT NULL,
    FOREIGN KEY (wh_code, cost_no)
        REFERENCES xlwms_cost_details(wh_code, cost_no) ON DELETE CASCADE,
    UNIQUE (wh_code, cost_no, item_index)
);

CREATE INDEX IF NOT EXISTS idx_xlwms_cost_items_name
    ON xlwms_cost_items (wh_code, bill_item_name);

CREATE TABLE IF NOT EXISTS xlwms_sync_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wh_code text REFERENCES xlwms_warehouses(wh_code),
    target text NOT NULL CHECK (target IN ('funds_flow', 'cost_details', 'integrated', 'stock_age', 'stock_flow', 'box_stock', 'box_stock_age', 'box_segment_age', 'box_stock_flow')),
    status text NOT NULL CHECK (status IN ('running', 'succeeded', 'failed')),
    pages integer NOT NULL DEFAULT 0,
    records_seen integer NOT NULL DEFAULT 0,
    records_saved integer NOT NULL DEFAULT 0,
    targets integer NOT NULL DEFAULT 0,
    succeeded integer NOT NULL DEFAULT 0,
    failed integer NOT NULL DEFAULT 0,
    cost_items integer NOT NULL DEFAULT 0,
    error_message text,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_xlwms_sync_runs_recent
    ON xlwms_sync_runs (started_at DESC);
CREATE INDEX IF NOT EXISTS idx_xlwms_sync_runs_warehouse
    ON xlwms_sync_runs (wh_code, started_at DESC);


CREATE TABLE IF NOT EXISTS xlwms_inventory_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_key text NOT NULL UNIQUE,
    inventory_kind text NOT NULL CHECK (inventory_kind IN (
        'integrated', 'stock_age', 'stock_flow', 'box_stock',
        'box_stock_age', 'box_segment_age', 'box_stock_flow'
    )),
    wh_code text NOT NULL REFERENCES xlwms_warehouses(wh_code),
    wh_name text,
    sku text,
    fnsku text,
    product_name text,
    box_type text,
    customize_barcode text,
    stock_type integer,
    product_type integer,
    total_amount numeric,
    product_total_amount numeric,
    box_total_amount numeric,
    fba_return_total_amount numeric,
    available_amount numeric,
    lock_amount numeric,
    transport_amount numeric,
    product_available_amount numeric,
    product_lock_amount numeric,
    product_transport_amount numeric,
    change_amount numeric,
    stock_age integer,
    stock_age_status integer,
    statistic_date date,
    shelf_date date,
    operate_time timestamp without time zone,
    relate_order_type integer,
    relate_order_type_name text,
    relate_order_no text,
    batch_no text,
    segment_one_quantity numeric,
    segment_two_quantity numeric,
    segment_three_quantity numeric,
    segment_four_quantity numeric,
    segment_five_quantity numeric,
    raw_payload jsonb NOT NULL,
    snapshot_token uuid,
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_xlwms_inventory_kind_warehouse
    ON xlwms_inventory_records (inventory_kind, wh_code);
CREATE INDEX IF NOT EXISTS idx_xlwms_inventory_sku
    ON xlwms_inventory_records (wh_code, sku);
CREATE INDEX IF NOT EXISTS idx_xlwms_inventory_box
    ON xlwms_inventory_records (wh_code, box_type, customize_barcode);
CREATE INDEX IF NOT EXISTS idx_xlwms_inventory_age
    ON xlwms_inventory_records (inventory_kind, stock_age DESC);
CREATE INDEX IF NOT EXISTS idx_xlwms_inventory_operate_time
    ON xlwms_inventory_records (inventory_kind, operate_time DESC);

ALTER TABLE xlwms_inventory_records
    ADD COLUMN IF NOT EXISTS product_available_amount numeric,
    ADD COLUMN IF NOT EXISTS product_lock_amount numeric,
    ADD COLUMN IF NOT EXISTS product_transport_amount numeric;

CREATE INDEX IF NOT EXISTS idx_xlwms_inventory_integrated_sku
    ON xlwms_inventory_records (sku, stock_type)
    WHERE inventory_kind = 'integrated';

CREATE TABLE IF NOT EXISTS xlwms_warehouse_sku_specs (
    warehouse_sku text PRIMARY KEY,
    product_name text,
    length_cm numeric,
    width_cm numeric,
    height_cm numeric,
    weight_kg numeric,
    note text,
    enabled boolean NOT NULL DEFAULT true,
    source text NOT NULL DEFAULT 'inventory',
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (length_cm IS NULL OR length_cm > 0),
    CHECK (width_cm IS NULL OR width_cm > 0),
    CHECK (height_cm IS NULL OR height_cm > 0),
    CHECK (weight_kg IS NULL OR weight_kg > 0)
);

CREATE INDEX IF NOT EXISTS idx_xlwms_warehouse_sku_specs_status
    ON xlwms_warehouse_sku_specs (enabled, warehouse_sku);

CREATE TABLE IF NOT EXISTS xlwms_inventory_threshold_defaults (
    id smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    east_threshold numeric NOT NULL DEFAULT 50 CHECK (east_threshold >= 0),
    west_threshold numeric NOT NULL DEFAULT 50 CHECK (west_threshold >= 0),
    total_threshold numeric NOT NULL DEFAULT 0 CHECK (total_threshold >= 0),
    updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO xlwms_inventory_threshold_defaults (id)
VALUES (1)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS xlwms_sku_inventory_thresholds (
    warehouse_sku text PRIMARY KEY REFERENCES xlwms_warehouse_sku_specs(warehouse_sku) ON DELETE CASCADE,
    east_threshold numeric NOT NULL CHECK (east_threshold >= 0),
    west_threshold numeric NOT NULL CHECK (west_threshold >= 0),
    total_threshold numeric NOT NULL CHECK (total_threshold >= 0),
    updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO xlwms_warehouse_sku_specs (warehouse_sku, product_name, source)
SELECT sku, max(product_name), 'inventory'
FROM xlwms_inventory_records
WHERE inventory_kind = 'integrated' AND NULLIF(BTRIM(sku), '') IS NOT NULL
GROUP BY sku
ON CONFLICT (warehouse_sku) DO UPDATE SET
    product_name = COALESCE(NULLIF(xlwms_warehouse_sku_specs.product_name, ''), EXCLUDED.product_name);

ALTER TABLE xlwms_sync_runs
    DROP CONSTRAINT IF EXISTS xlwms_sync_runs_target_check;
ALTER TABLE xlwms_sync_runs
    ADD CONSTRAINT xlwms_sync_runs_target_check CHECK (target IN (
        'funds_flow', 'cost_details', 'integrated', 'stock_age', 'stock_flow',
        'box_stock', 'box_stock_age', 'box_segment_age', 'box_stock_flow'
    ));
