CREATE TABLE IF NOT EXISTS xlwms_warehouses (
    wh_code text PRIMARY KEY,
    warehouse_name text,
    api_base_url text NOT NULL,
    app_key_ciphertext text NOT NULL,
    app_secret_ciphertext text NOT NULL,
    app_key_hint text NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    disabled_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE xlwms_warehouses
    ADD COLUMN IF NOT EXISTS oms_username_ciphertext text,
    ADD COLUMN IF NOT EXISTS oms_password_ciphertext text,
    ADD COLUMN IF NOT EXISTS oms_account_hint text;

CREATE TABLE IF NOT EXISTS xlwms_oms_accounts (
    account_key text PRIMARY KEY,
    username_ciphertext text NOT NULL,
    password_ciphertext text NOT NULL,
    account_hint text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_xlwms_warehouses_active
    ON xlwms_warehouses (wh_code) WHERE is_active;

CREATE TABLE IF NOT EXISTS xlwms_funds_flows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key text NOT NULL UNIQUE,
    wh_code text NOT NULL REFERENCES xlwms_warehouses(wh_code),
    order_no text,
    platform_order_no text,
    cost_total numeric,
    currency_code text,
    cost_status integer,
    module_type integer,
    cost_time timestamp without time zone,
    bill_status integer,
    relate_bill_no text,
    raw_payload jsonb NOT NULL,
    snapshot_token uuid,
    detail_sync_status text NOT NULL DEFAULT 'pending',
    detail_attempts integer NOT NULL DEFAULT 0,
    detail_last_attempt_at timestamptz,
    detail_error_code text,
    detail_error_message text,
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE xlwms_funds_flows
    ADD COLUMN IF NOT EXISTS snapshot_token uuid,
    ADD COLUMN IF NOT EXISTS detail_sync_status text NOT NULL DEFAULT 'pending',
    ADD COLUMN IF NOT EXISTS detail_attempts integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS detail_last_attempt_at timestamptz,
    ADD COLUMN IF NOT EXISTS detail_error_code text,
    ADD COLUMN IF NOT EXISTS detail_error_message text;

CREATE INDEX IF NOT EXISTS idx_xlwms_funds_flows_order
    ON xlwms_funds_flows (wh_code, order_no);
CREATE INDEX IF NOT EXISTS idx_xlwms_funds_flows_platform_order
    ON xlwms_funds_flows (wh_code, platform_order_no);
CREATE INDEX IF NOT EXISTS idx_xlwms_funds_flows_cost_time
    ON xlwms_funds_flows (wh_code, cost_time DESC);
CREATE INDEX IF NOT EXISTS idx_xlwms_funds_flows_module_status
    ON xlwms_funds_flows (wh_code, module_type, cost_status, bill_status);

CREATE TABLE IF NOT EXISTS xlwms_cost_details (
    wh_code text NOT NULL REFERENCES xlwms_warehouses(wh_code),
    cost_no text NOT NULL,
    query_order_no text NOT NULL,
    query_order_type integer NOT NULL,
    cost_total numeric,
    bill_status integer,
    module_type integer,
    currency_code text,
    cost_status integer,
    create_time timestamp without time zone,
    platform_order_no text,
    relate_bill_no text,
    raw_payload jsonb NOT NULL,
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_fetched_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (wh_code, cost_no),
    CHECK (query_order_type IN (1, 2))
);

CREATE INDEX IF NOT EXISTS idx_xlwms_cost_details_query_order
    ON xlwms_cost_details (wh_code, query_order_no, query_order_type);
CREATE INDEX IF NOT EXISTS idx_xlwms_cost_details_platform_order
    ON xlwms_cost_details (wh_code, platform_order_no);

CREATE TABLE IF NOT EXISTS xlwms_cost_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wh_code text NOT NULL,
    cost_no text NOT NULL,
    item_index integer NOT NULL,
    bill_item_name text,
    bill_item_total numeric,
    charge_time timestamp without time zone,
    raw_payload jsonb NOT NULL,
    FOREIGN KEY (wh_code, cost_no)
        REFERENCES xlwms_cost_details(wh_code, cost_no) ON DELETE CASCADE,
    UNIQUE (wh_code, cost_no, item_index)
);

CREATE INDEX IF NOT EXISTS idx_xlwms_cost_items_name
    ON xlwms_cost_items (wh_code, bill_item_name);

CREATE TABLE IF NOT EXISTS xlwms_sync_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wh_code text REFERENCES xlwms_warehouses(wh_code),
    target text NOT NULL CHECK (target IN ('funds_flow', 'cost_details', 'integrated', 'stock_age', 'stock_flow', 'box_stock', 'box_stock_age', 'box_segment_age', 'box_stock_flow')),
    status text NOT NULL CHECK (status IN ('running', 'succeeded', 'failed')),
    pages integer NOT NULL DEFAULT 0,
    records_seen integer NOT NULL DEFAULT 0,
    records_saved integer NOT NULL DEFAULT 0,
    targets integer NOT NULL DEFAULT 0,
    succeeded integer NOT NULL DEFAULT 0,
    failed integer NOT NULL DEFAULT 0,
    cost_items integer NOT NULL DEFAULT 0,
    error_message text,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_xlwms_sync_runs_recent
    ON xlwms_sync_runs (started_at DESC);
CREATE INDEX IF NOT EXISTS idx_xlwms_sync_runs_warehouse
    ON xlwms_sync_runs (wh_code, started_at DESC);


CREATE TABLE IF NOT EXISTS xlwms_inventory_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_key text NOT NULL UNIQUE,
    inventory_kind text NOT NULL CHECK (inventory_kind IN (
        'integrated', 'stock_age', 'stock_flow', 'box_stock',
        'box_stock_age', 'box_segment_age', 'box_stock_flow'
    )),
    wh_code text NOT NULL REFERENCES xlwms_warehouses(wh_code),
    wh_name text,
    sku text,
    fnsku text,
    product_name text,
    box_type text,
    customize_barcode text,
    stock_type integer,
    product_type integer,
    total_amount numeric,
    product_total_amount numeric,
    box_total_amount numeric,
    fba_return_total_amount numeric,
    available_amount numeric,
    lock_amount numeric,
    transport_amount numeric,
    product_available_amount numeric,
    product_lock_amount numeric,
    product_transport_amount numeric,
    change_amount numeric,
    stock_age integer,
    stock_age_status integer,
    statistic_date date,
    shelf_date date,
    operate_time timestamp without time zone,
    relate_order_type integer,
    relate_order_type_name text,
    relate_order_no text,
    batch_no text,
    segment_one_quantity numeric,
    segment_two_quantity numeric,
    segment_three_quantity numeric,
    segment_four_quantity numeric,
    segment_five_quantity numeric,
    raw_payload jsonb NOT NULL,
    snapshot_token uuid,
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_xlwms_inventory_kind_warehouse
    ON xlwms_inventory_records (inventory_kind, wh_code);
CREATE INDEX IF NOT EXISTS idx_xlwms_inventory_sku
    ON xlwms_inventory_records (wh_code, sku);
CREATE INDEX IF NOT EXISTS idx_xlwms_inventory_box
    ON xlwms_inventory_records (wh_code, box_type, customize_barcode);
CREATE INDEX IF NOT EXISTS idx_xlwms_inventory_age
    ON xlwms_inventory_records (inventory_kind, stock_age DESC);
CREATE INDEX IF NOT EXISTS idx_xlwms_inventory_operate_time
    ON xlwms_inventory_records (inventory_kind, operate_time DESC);

ALTER TABLE xlwms_inventory_records
    ADD COLUMN IF NOT EXISTS product_available_amount numeric,
    ADD COLUMN IF NOT EXISTS product_lock_amount numeric,
    ADD COLUMN IF NOT EXISTS product_transport_amount numeric;

CREATE INDEX IF NOT EXISTS idx_xlwms_inventory_integrated_sku
    ON xlwms_inventory_records (sku, stock_type)
    WHERE inventory_kind = 'integrated';

CREATE TABLE IF NOT EXISTS xlwms_warehouse_sku_specs (
    warehouse_sku text PRIMARY KEY,
    product_name text,
    length_cm numeric,
    width_cm numeric,
    height_cm numeric,
    weight_kg numeric,
    note text,
    enabled boolean NOT NULL DEFAULT true,
    source text NOT NULL DEFAULT 'inventory',
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (length_cm IS NULL OR length_cm > 0),
    CHECK (width_cm IS NULL OR width_cm > 0),
    CHECK (height_cm IS NULL OR height_cm > 0),
    CHECK (weight_kg IS NULL OR weight_kg > 0)
);

CREATE INDEX IF NOT EXISTS idx_xlwms_warehouse_sku_specs_status
    ON xlwms_warehouse_sku_specs (enabled, warehouse_sku);

CREATE TABLE IF NOT EXISTS xlwms_sku_combinations (
    id bigserial PRIMARY KEY,
    name text NOT NULL,
    substitute_for_sku text UNIQUE REFERENCES xlwms_warehouse_sku_specs(warehouse_sku) ON DELETE RESTRICT,
    length_cm numeric NOT NULL CHECK (length_cm > 0),
    width_cm numeric NOT NULL CHECK (width_cm > 0),
    height_cm numeric NOT NULL CHECK (height_cm > 0),
    weight_kg numeric NOT NULL CHECK (weight_kg > 0),
    calculated_length_cm numeric CHECK (calculated_length_cm IS NULL OR calculated_length_cm > 0),
    calculated_width_cm numeric CHECK (calculated_width_cm IS NULL OR calculated_width_cm > 0),
    calculated_height_cm numeric CHECK (calculated_height_cm IS NULL OR calculated_height_cm > 0),
    calculated_weight_kg numeric CHECK (calculated_weight_kg IS NULL OR calculated_weight_kg > 0),
    note text NOT NULL DEFAULT '',
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (length(btrim(name)) BETWEEN 1 AND 120)
);

CREATE INDEX IF NOT EXISTS idx_xlwms_sku_combinations_status
    ON xlwms_sku_combinations (enabled, updated_at DESC);

CREATE TABLE IF NOT EXISTS xlwms_sku_combination_items (
    combination_id bigint NOT NULL REFERENCES xlwms_sku_combinations(id) ON DELETE CASCADE,
    warehouse_sku text NOT NULL REFERENCES xlwms_warehouse_sku_specs(warehouse_sku) ON DELETE RESTRICT,
    quantity integer NOT NULL CHECK (quantity > 0 AND quantity <= 300),
    PRIMARY KEY (combination_id, warehouse_sku)
);

CREATE INDEX IF NOT EXISTS idx_xlwms_sku_combination_items_sku
    ON xlwms_sku_combination_items (warehouse_sku, combination_id);

CREATE TABLE IF NOT EXISTS xlwms_inventory_corrections (
    wh_code text NOT NULL REFERENCES xlwms_warehouses(wh_code) ON DELETE CASCADE,
    warehouse_sku text NOT NULL REFERENCES xlwms_warehouse_sku_specs(warehouse_sku) ON DELETE CASCADE,
    corrected_available_amount numeric NOT NULL DEFAULT 0 CHECK (corrected_available_amount >= 0),
    note text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (wh_code, warehouse_sku)
);

ALTER TABLE xlwms_inventory_corrections
    ADD COLUMN IF NOT EXISTS correction_mode text NOT NULL DEFAULT 'absolute',
    ADD COLUMN IF NOT EXISTS correction_amount numeric NOT NULL DEFAULT 0;

UPDATE xlwms_inventory_corrections
SET correction_amount=corrected_available_amount
WHERE correction_mode='absolute' AND correction_amount=0 AND corrected_available_amount<>0;

ALTER TABLE xlwms_inventory_corrections
    DROP CONSTRAINT IF EXISTS xlwms_inventory_corrections_mode_check,
    DROP CONSTRAINT IF EXISTS xlwms_inventory_corrections_amount_check;
ALTER TABLE xlwms_inventory_corrections
    ADD CONSTRAINT xlwms_inventory_corrections_mode_check CHECK (correction_mode IN ('absolute', 'subtract')),
    ADD CONSTRAINT xlwms_inventory_corrections_amount_check CHECK (correction_amount >= 0);

CREATE INDEX IF NOT EXISTS idx_xlwms_inventory_corrections_sku
    ON xlwms_inventory_corrections (warehouse_sku, wh_code);

CREATE TABLE IF NOT EXISTS xlwms_fulfillment_shops (
    platform text NOT NULL CHECK (platform IN ('temu', 'shein')),
    shop_code text NOT NULL CHECK (shop_code ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    shop_name text NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (platform, shop_code)
);

INSERT INTO xlwms_fulfillment_shops (platform, shop_code, shop_name)
VALUES
    ('temu', 'panda-homes', 'PANDA HOMES'),
    ('temu', 'panda-buy', 'PANDA BUY'),
    ('shein', 'beauty-hangers-home', 'Beauty Hangers home')
ON CONFLICT (platform, shop_code) DO UPDATE SET
    shop_name = EXCLUDED.shop_name,
    enabled = true,
    updated_at = now();

CREATE TABLE IF NOT EXISTS xlwms_platform_inventory_thresholds (
    platform text PRIMARY KEY CHECK (platform IN ('temu', 'shein')),
    east_threshold numeric NOT NULL CHECK (east_threshold >= 0),
    west_threshold numeric NOT NULL CHECK (west_threshold >= 0),
    total_threshold numeric NOT NULL CHECK (total_threshold >= 0),
    updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO xlwms_platform_inventory_thresholds (
    platform, east_threshold, west_threshold, total_threshold
)
VALUES ('temu', 0, 0, 0), ('shein', 0, 0, 0)
ON CONFLICT (platform) DO NOTHING;

CREATE TABLE IF NOT EXISTS xlwms_platform_sku_inventory_thresholds (
    platform text NOT NULL REFERENCES xlwms_platform_inventory_thresholds(platform) ON DELETE CASCADE,
    warehouse_sku text NOT NULL REFERENCES xlwms_warehouse_sku_specs(warehouse_sku) ON DELETE CASCADE,
    east_threshold numeric NOT NULL CHECK (east_threshold >= 0),
    west_threshold numeric NOT NULL CHECK (west_threshold >= 0),
    total_threshold numeric NOT NULL CHECK (total_threshold >= 0),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (platform, warehouse_sku)
);

CREATE TABLE IF NOT EXISTS xlwms_platform_carrier_policies (
    platform text NOT NULL CHECK (platform IN ('temu', 'shein')),
    warehouse_key text NOT NULL CHECK (warehouse_key IN ('DPS002', 'ARP_EAST', 'DPS004', 'ARP_WEST')),
    carrier_code text NOT NULL CHECK (carrier_code IN ('GOFO', 'SWIFTX', 'SPEEDX', 'YANWEN', 'UPS', 'USPS', 'FEDEX')),
    priority integer NOT NULL CHECK (priority BETWEEN 1 AND 7),
    enabled boolean NOT NULL DEFAULT true,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (platform, warehouse_key, carrier_code),
    UNIQUE (platform, warehouse_key, priority)
);

INSERT INTO xlwms_platform_carrier_policies(platform, warehouse_key, carrier_code, priority, enabled)
SELECT platform, warehouse_key, carrier_code, priority,
       NOT (platform='shein' AND warehouse_key='ARP_EAST' AND carrier_code='SWIFTX')
FROM (VALUES ('temu'), ('shein')) platforms(platform)
CROSS JOIN (VALUES ('DPS002'), ('ARP_EAST'), ('DPS004'), ('ARP_WEST')) warehouses(warehouse_key)
CROSS JOIN (VALUES
    ('GOFO', 1), ('SWIFTX', 2), ('SPEEDX', 3), ('YANWEN', 4),
    ('UPS', 5), ('USPS', 6), ('FEDEX', 7)
) carriers(carrier_code, priority)
ON CONFLICT (platform, warehouse_key, carrier_code) DO NOTHING;

CREATE TABLE IF NOT EXISTS xlwms_platform_warehouse_carrier_rules (
    platform text NOT NULL CHECK (platform IN ('temu', 'shein')),
    warehouse_key text NOT NULL CHECK (warehouse_key IN ('DPS002', 'ARP_EAST', 'DPS004', 'ARP_WEST')),
    allowed_carrier_codes text[] NOT NULL DEFAULT '{}',
    allow_signature boolean NOT NULL DEFAULT true,
    allowed_currency_codes text[] NOT NULL DEFAULT '{}',
    selection_mode text NOT NULL CHECK (selection_mode IN ('lowest_price', 'carrier_priority_within_delta')),
    max_price_delta numeric NOT NULL DEFAULT 0 CHECK (max_price_delta >= 0),
    warehouse_tie_priority integer NOT NULL CHECK (warehouse_tie_priority > 0),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (platform, warehouse_key)
);

INSERT INTO xlwms_platform_warehouse_carrier_rules (
    platform, warehouse_key, allowed_carrier_codes, allow_signature,
    allowed_currency_codes, selection_mode, max_price_delta, warehouse_tie_priority
)
SELECT platform, warehouse_key,
       ARRAY['GOFO','SWIFTX','SPEEDX','YANWEN','UPS','USPS','FEDEX']::text[],
       platform='shein',
       CASE WHEN platform='temu' THEN ARRAY['USD']::text[] ELSE ARRAY[]::text[] END,
       CASE WHEN platform='temu' THEN 'carrier_priority_within_delta' ELSE 'lowest_price' END,
       CASE WHEN platform='temu' THEN 0.50 ELSE 0 END,
       CASE
           WHEN platform='temu' AND warehouse_key LIKE 'DPS%' THEN 1
           WHEN platform='temu' THEN 2
           WHEN platform='shein' AND warehouse_key LIKE 'ARP%' THEN 1
           ELSE 2
       END
FROM (VALUES ('temu'), ('shein')) platforms(platform)
CROSS JOIN (VALUES ('DPS002'), ('ARP_EAST'), ('DPS004'), ('ARP_WEST')) warehouses(warehouse_key)
ON CONFLICT (platform, warehouse_key) DO NOTHING;

CREATE TABLE IF NOT EXISTS xlwms_platform_sku_carrier_policies (
    platform text NOT NULL CHECK (platform IN ('temu', 'shein')),
    warehouse_sku text NOT NULL,
    warehouse_key text NOT NULL CHECK (warehouse_key IN ('DPS002', 'ARP_EAST', 'DPS004', 'ARP_WEST')),
    carrier_code text NOT NULL CHECK (carrier_code IN ('GOFO', 'SWIFTX', 'SPEEDX', 'YANWEN', 'UPS', 'USPS', 'FEDEX')),
    priority integer NOT NULL CHECK (priority BETWEEN 1 AND 7),
    enabled boolean NOT NULL DEFAULT true,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (platform, warehouse_sku, warehouse_key, carrier_code),
    UNIQUE (platform, warehouse_sku, warehouse_key, priority)
);

CREATE INDEX IF NOT EXISTS xlwms_platform_sku_carrier_lookup_idx
    ON xlwms_platform_sku_carrier_policies(platform, warehouse_sku, warehouse_key);

CREATE TABLE IF NOT EXISTS xlwms_platform_sku_disabled_warehouses (
    platform text NOT NULL CHECK (platform IN ('temu', 'shein')),
    warehouse_sku text NOT NULL,
    warehouse_key text NOT NULL CHECK (warehouse_key IN ('DPS002', 'ARP_EAST', 'DPS004', 'ARP_WEST')),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (platform, warehouse_sku, warehouse_key)
);

CREATE INDEX IF NOT EXISTS xlwms_platform_sku_disabled_warehouse_lookup_idx
    ON xlwms_platform_sku_disabled_warehouses(platform, warehouse_sku);

DO $inventory_threshold_migration$
DECLARE
    conflict_count integer;
    missing_count integer;
BEGIN
    IF to_regclass('xlwms_inventory_threshold_defaults') IS NOT NULL THEN
        EXECUTE $sql$
            UPDATE xlwms_platform_inventory_thresholds target
            SET east_threshold=source.east_threshold,
                west_threshold=source.west_threshold,
                total_threshold=source.total_threshold,
                updated_at=source.updated_at
            FROM xlwms_inventory_threshold_defaults source
            WHERE source.id=1
        $sql$;
        EXECUTE $sql$
            SELECT count(*)
            FROM xlwms_inventory_threshold_defaults source
            CROSS JOIN xlwms_platform_inventory_thresholds target
            WHERE source.id=1 AND (
                target.east_threshold IS DISTINCT FROM source.east_threshold OR
                target.west_threshold IS DISTINCT FROM source.west_threshold OR
                target.total_threshold IS DISTINCT FROM source.total_threshold
            )
        $sql$ INTO missing_count;
        IF missing_count > 0 THEN
            RAISE EXCEPTION 'inventory threshold migration failed to verify % platform default rows', missing_count;
        END IF;
    END IF;

    IF to_regclass('xlwms_shop_inventory_thresholds') IS NOT NULL THEN
        EXECUTE $sql$
            SELECT count(*) FROM (
                SELECT platform
                FROM xlwms_shop_inventory_thresholds
                GROUP BY platform
                HAVING count(DISTINCT ROW(east_threshold, west_threshold, total_threshold)) > 1
            ) conflicts
        $sql$ INTO conflict_count;
        IF conflict_count > 0 THEN
            RAISE EXCEPTION 'inventory threshold migration found % platform default conflicts', conflict_count;
        END IF;
        EXECUTE $sql$
            INSERT INTO xlwms_platform_inventory_thresholds (
                platform, east_threshold, west_threshold, total_threshold, updated_at
            )
            SELECT platform, min(east_threshold), min(west_threshold), min(total_threshold), max(updated_at)
            FROM xlwms_shop_inventory_thresholds
            GROUP BY platform
            ON CONFLICT (platform) DO UPDATE SET
                east_threshold=EXCLUDED.east_threshold,
                west_threshold=EXCLUDED.west_threshold,
                total_threshold=EXCLUDED.total_threshold,
                updated_at=EXCLUDED.updated_at
        $sql$;
        EXECUTE $sql$
            SELECT count(*)
            FROM (
                SELECT platform, min(east_threshold) AS east_threshold,
                       min(west_threshold) AS west_threshold,
                       min(total_threshold) AS total_threshold
                FROM xlwms_shop_inventory_thresholds
                GROUP BY platform
            ) source
            LEFT JOIN xlwms_platform_inventory_thresholds target ON target.platform=source.platform
            WHERE target.platform IS NULL OR
                  target.east_threshold IS DISTINCT FROM source.east_threshold OR
                  target.west_threshold IS DISTINCT FROM source.west_threshold OR
                  target.total_threshold IS DISTINCT FROM source.total_threshold
        $sql$ INTO missing_count;
        IF missing_count > 0 THEN
            RAISE EXCEPTION 'inventory threshold migration failed to verify % shop default rows', missing_count;
        END IF;
    END IF;

    IF to_regclass('xlwms_sku_inventory_thresholds') IS NOT NULL THEN
        EXECUTE $sql$
            INSERT INTO xlwms_platform_sku_inventory_thresholds (
                platform, warehouse_sku, east_threshold, west_threshold, total_threshold, updated_at
            )
            SELECT platform.platform, source.warehouse_sku, source.east_threshold,
                   source.west_threshold, source.total_threshold, source.updated_at
            FROM xlwms_sku_inventory_thresholds source
            CROSS JOIN xlwms_platform_inventory_thresholds platform
            ON CONFLICT (platform, warehouse_sku) DO NOTHING
        $sql$;
        EXECUTE $sql$
            SELECT count(*)
            FROM xlwms_sku_inventory_thresholds source
            CROSS JOIN xlwms_platform_inventory_thresholds platform
            LEFT JOIN xlwms_platform_sku_inventory_thresholds target
              ON target.platform=platform.platform AND target.warehouse_sku=source.warehouse_sku
            WHERE target.warehouse_sku IS NULL OR
                  target.east_threshold IS DISTINCT FROM source.east_threshold OR
                  target.west_threshold IS DISTINCT FROM source.west_threshold OR
                  target.total_threshold IS DISTINCT FROM source.total_threshold
        $sql$ INTO missing_count;
        IF missing_count > 0 THEN
            RAISE EXCEPTION 'inventory threshold migration failed to verify % global SKU rows', missing_count;
        END IF;
    END IF;

    IF to_regclass('xlwms_shop_sku_inventory_thresholds') IS NOT NULL THEN
        EXECUTE $sql$
            SELECT count(*) FROM (
                SELECT platform, warehouse_sku
                FROM xlwms_shop_sku_inventory_thresholds
                GROUP BY platform, warehouse_sku
                HAVING count(DISTINCT ROW(east_threshold, west_threshold, total_threshold)) > 1
            ) conflicts
        $sql$ INTO conflict_count;
        IF conflict_count > 0 THEN
            RAISE EXCEPTION 'inventory threshold migration found % platform SKU conflicts', conflict_count;
        END IF;
        EXECUTE $sql$
            INSERT INTO xlwms_platform_sku_inventory_thresholds (
                platform, warehouse_sku, east_threshold, west_threshold, total_threshold, updated_at
            )
            SELECT platform, warehouse_sku, min(east_threshold), min(west_threshold),
                   min(total_threshold), max(updated_at)
            FROM xlwms_shop_sku_inventory_thresholds
            GROUP BY platform, warehouse_sku
            ON CONFLICT (platform, warehouse_sku) DO UPDATE SET
                east_threshold=EXCLUDED.east_threshold,
                west_threshold=EXCLUDED.west_threshold,
                total_threshold=EXCLUDED.total_threshold,
                updated_at=EXCLUDED.updated_at
        $sql$;
        EXECUTE $sql$
            SELECT count(*)
            FROM (
                SELECT platform, warehouse_sku, min(east_threshold) AS east_threshold,
                       min(west_threshold) AS west_threshold,
                       min(total_threshold) AS total_threshold
                FROM xlwms_shop_sku_inventory_thresholds
                GROUP BY platform, warehouse_sku
            ) source
            LEFT JOIN xlwms_platform_sku_inventory_thresholds target
              ON target.platform=source.platform AND target.warehouse_sku=source.warehouse_sku
            WHERE target.warehouse_sku IS NULL OR
                  target.east_threshold IS DISTINCT FROM source.east_threshold OR
                  target.west_threshold IS DISTINCT FROM source.west_threshold OR
                  target.total_threshold IS DISTINCT FROM source.total_threshold
        $sql$ INTO missing_count;
        IF missing_count > 0 THEN
            RAISE EXCEPTION 'inventory threshold migration failed to verify % platform SKU rows', missing_count;
        END IF;
    END IF;
END
$inventory_threshold_migration$;

DROP TABLE IF EXISTS xlwms_shop_sku_inventory_thresholds;
DROP TABLE IF EXISTS xlwms_shop_inventory_thresholds;
DROP TABLE IF EXISTS xlwms_sku_inventory_thresholds;
DROP TABLE IF EXISTS xlwms_inventory_threshold_defaults;

CREATE TABLE IF NOT EXISTS xlwms_inventory_alert_defaults (
    id smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    threshold numeric NOT NULL DEFAULT 100 CHECK (threshold >= 0),
    updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO xlwms_inventory_alert_defaults (id)
VALUES (1)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS xlwms_warehouse_sku_alert_thresholds (
    wh_code text NOT NULL REFERENCES xlwms_warehouses(wh_code) ON DELETE CASCADE,
    warehouse_sku text NOT NULL REFERENCES xlwms_warehouse_sku_specs(warehouse_sku) ON DELETE CASCADE,
    threshold numeric NOT NULL CHECK (threshold >= 0),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (wh_code, warehouse_sku)
);

CREATE INDEX IF NOT EXISTS idx_xlwms_warehouse_sku_alert_thresholds_sku
    ON xlwms_warehouse_sku_alert_thresholds (warehouse_sku, wh_code);

INSERT INTO xlwms_warehouse_sku_specs (warehouse_sku, product_name, source)
SELECT sku, max(product_name), 'inventory'
FROM xlwms_inventory_records
WHERE inventory_kind = 'integrated' AND NULLIF(BTRIM(sku), '') IS NOT NULL
GROUP BY sku
ON CONFLICT (warehouse_sku) DO UPDATE SET
    product_name = COALESCE(NULLIF(xlwms_warehouse_sku_specs.product_name, ''), EXCLUDED.product_name);

ALTER TABLE xlwms_sync_runs
    DROP CONSTRAINT IF EXISTS xlwms_sync_runs_target_check;
ALTER TABLE xlwms_sync_runs
    ADD CONSTRAINT xlwms_sync_runs_target_check CHECK (target IN (
        'funds_flow', 'cost_details', 'integrated', 'stock_age', 'stock_flow',
        'box_stock', 'box_stock_age', 'box_segment_age', 'box_stock_flow'
    ));

CREATE TABLE IF NOT EXISTS xlwms_fulfillment_audits (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform text NOT NULL,
    shop_code text NOT NULL,
    shop_name text NOT NULL DEFAULT '',
    platform_order_no text NOT NULL,
    platform_status text NOT NULL,
    platform_status_code integer,
    platform_shipping_at timestamptz,
    warehouse_key text NOT NULL DEFAULT '',
    wh_code text NOT NULL DEFAULT '',
    tracking_number text NOT NULL DEFAULT '',
    oms_status text NOT NULL DEFAULT 'pending_query',
    oms_status_code integer,
    oms_status_since timestamptz NOT NULL DEFAULT now(),
    oms_processing_since timestamptz,
    oms_order_created_at timestamptz,
    oms_outbound_at timestamptz,
    outbound_order_no text NOT NULL DEFAULT '',
    oms_tracking_number text NOT NULL DEFAULT '',
    exception_category text NOT NULL DEFAULT 'pending_query',
    sync_error text NOT NULL DEFAULT '',
    active boolean NOT NULL DEFAULT true,
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
	last_checked_at timestamptz,
	resolved_at timestamptz,
	terminal_status text NOT NULL DEFAULT '',
	terminal_note text NOT NULL DEFAULT '',
	manual_resolved_at timestamptz,
	updated_at timestamptz NOT NULL DEFAULT now(),
	UNIQUE (platform, shop_code, platform_order_no)
);

ALTER TABLE xlwms_fulfillment_audits
    ADD COLUMN IF NOT EXISTS last_mile_tracking_number text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS tracking_status text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS tracking_status_text text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS tracking_updated_at timestamptz,
    ADD COLUMN IF NOT EXISTS tracking_checked_at timestamptz,
    ADD COLUMN IF NOT EXISTS tracking_error text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS tracking_category text NOT NULL DEFAULT 'awaiting_pickup',
    ADD COLUMN IF NOT EXISTS tracking_package_count integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS picked_up_package_count integer NOT NULL DEFAULT 0,
	ADD COLUMN IF NOT EXISTS pickup_exception_reason text NOT NULL DEFAULT '',
	ADD COLUMN IF NOT EXISTS pickup_confirmed_at timestamptz,
	ADD COLUMN IF NOT EXISTS terminal_status text NOT NULL DEFAULT '',
	ADD COLUMN IF NOT EXISTS terminal_note text NOT NULL DEFAULT '',
	ADD COLUMN IF NOT EXISTS manual_resolved_at timestamptz;

ALTER TABLE xlwms_fulfillment_audits
    DROP CONSTRAINT IF EXISTS xlwms_fulfillment_audits_terminal_status_check,
    ADD CONSTRAINT xlwms_fulfillment_audits_terminal_status_check CHECK (
        terminal_status IN ('', 'manually_fulfilled', 'cancelled', 'not_required', 'other')
    );

CREATE INDEX IF NOT EXISTS idx_xlwms_fulfillment_audits_tracking
    ON xlwms_fulfillment_audits (tracking_category, wh_code, shop_code, oms_outbound_at DESC);

CREATE INDEX IF NOT EXISTS idx_xlwms_fulfillment_audits_queue
    ON xlwms_fulfillment_audits (active, last_checked_at, updated_at);
CREATE INDEX IF NOT EXISTS idx_xlwms_fulfillment_audits_filters
    ON xlwms_fulfillment_audits (shop_code, wh_code, exception_category, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_xlwms_fulfillment_audits_order
    ON xlwms_fulfillment_audits (platform_order_no);
CREATE INDEX IF NOT EXISTS idx_xlwms_fulfillment_audits_manual_resolved
    ON xlwms_fulfillment_audits (manual_resolved_at DESC)
    WHERE terminal_status<>'';

CREATE TABLE IF NOT EXISTS xlwms_fulfillment_tracking_watermarks (
    queue_name text PRIMARY KEY,
    cursor_audit_id bigint NOT NULL DEFAULT 0,
    last_batch_at timestamptz,
    last_batch_count integer NOT NULL DEFAULT 0,
    last_failed_count integer NOT NULL DEFAULT 0,
    last_cycle_completed_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (queue_name IN ('pickup_exception', 'regular'))
);

CREATE TABLE IF NOT EXISTS xlwms_outbound_order_index (
    account_key text NOT NULL,
    wh_code text NOT NULL DEFAULT '',
    outbound_order_no text NOT NULL,
    third_order_no text NOT NULL DEFAULT '',
    refer_order_no text NOT NULL DEFAULT '',
    platform_order_no text NOT NULL DEFAULT '',
    status integer NOT NULL,
    tracking_number text NOT NULL DEFAULT '',
    order_created_at timestamptz,
    outbound_at timestamptz,
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (account_key, outbound_order_no)
);

CREATE INDEX IF NOT EXISTS idx_xlwms_outbound_order_index_platform
    ON xlwms_outbound_order_index (upper(platform_order_no));
CREATE INDEX IF NOT EXISTS idx_xlwms_outbound_order_index_third
    ON xlwms_outbound_order_index (upper(third_order_no));
CREATE INDEX IF NOT EXISTS idx_xlwms_outbound_order_index_refer
    ON xlwms_outbound_order_index (upper(refer_order_no));
CREATE INDEX IF NOT EXISTS idx_xlwms_outbound_order_index_tracking
    ON xlwms_outbound_order_index (upper(tracking_number));
CREATE INDEX IF NOT EXISTS idx_xlwms_outbound_order_index_warehouse_created
    ON xlwms_outbound_order_index (wh_code, order_created_at DESC);

CREATE TABLE IF NOT EXISTS xlwms_outbound_sync_watermarks (
    account_key text PRIMARY KEY,
    credential_code text NOT NULL DEFAULT '',
    coverage_started_at timestamptz,
    watermark_at timestamptz,
    last_completed_at timestamptz,
    last_error text NOT NULL DEFAULT '',
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS xlwms_outbound_sync_windows (
    account_key text NOT NULL,
    window_start timestamptz NOT NULL,
    window_end timestamptz NOT NULL,
    record_count integer NOT NULL DEFAULT 0,
    completed_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (account_key, window_start)
);

CREATE INDEX IF NOT EXISTS idx_xlwms_outbound_sync_windows_completed
    ON xlwms_outbound_sync_windows (completed_at DESC);

ALTER TABLE xlwms_outbound_sync_watermarks
    ADD COLUMN IF NOT EXISTS coverage_started_at timestamptz;
UPDATE xlwms_outbound_sync_watermarks
SET coverage_started_at=watermark_at-interval '24 hours'
WHERE coverage_started_at IS NULL AND watermark_at IS NOT NULL;

INSERT INTO xlwms_outbound_sync_windows (account_key,window_start,window_end,record_count)
SELECT watermark.account_key,window_start,window_start+interval '1 hour',0
FROM xlwms_outbound_sync_watermarks watermark
CROSS JOIN LATERAL generate_series(
    date_trunc('hour',watermark.coverage_started_at),
    date_trunc('hour',watermark.watermark_at)-interval '1 hour',
    interval '1 hour'
) window_start
WHERE watermark.coverage_started_at IS NOT NULL AND watermark.watermark_at IS NOT NULL
ON CONFLICT (account_key,window_start) DO NOTHING;
