import { RefreshCw, Search } from "lucide-react";
import { useEffect, useState } from "react";
import { api } from "../api";
import { EmptyState, ErrorState, LoadingState, PageHeader, Pagination, StatusBadge, dateTime, money } from "../components/Common";
import type { CostDetail, FundsFlow, PageData } from "../types";

export default function CostsPage({warehouse}:{warehouse:string}){
  const [tab,setTab]=useState<"flows"|"details">("flows"); const [search,setSearch]=useState(""); const [status,setStatus]=useState(""); const [page,setPage]=useState(1); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [flows,setFlows]=useState<PageData<FundsFlow>|null>(null); const [details,setDetails]=useState<PageData<CostDetail>|null>(null);
  const load=async()=>{setLoading(true);setError("");try{if(tab==="flows")setFlows(await api.fundsFlows({warehouse:warehouse||undefined,q:search,detailStatus:status,page,pageSize:30}));else setDetails(await api.costDetails({warehouse:warehouse||undefined,q:search,page,pageSize:30}));}catch(reason){setError(reason instanceof Error?reason.message:"无法加载费用数据");}finally{setLoading(false);}};
  useEffect(()=>{void load();},[tab,warehouse,search,status,page]); const changeTab=(value:"flows"|"details")=>{setTab(value);setPage(1);setStatus("");}; const active=tab==="flows"?flows:details;
  return <><PageHeader title="费用中心" subtitle="资金流水与费用项目明细" actions={<button className="icon-button bordered" onClick={()=>void load()} title="刷新"><RefreshCw size={18}/></button>}/><div className="segmented-tabs compact-tabs"><button className={tab==="flows"?"active":""} onClick={()=>changeTab("flows")}>资金流水</button><button className={tab==="details"?"active":""} onClick={()=>changeTab("details")}>费用明细</button></div><div className="filter-bar"><label className="search-field"><Search size={17}/><input value={search} onChange={event=>{setSearch(event.target.value);setPage(1);}} placeholder="订单号、平台单号或费用单号"/></label>{tab==="flows"&&<label className="select-field"><select value={status} onChange={event=>{setStatus(event.target.value);setPage(1);}}><option value="">全部明细状态</option><option value="pending">待同步</option><option value="success">已同步</option><option value="error">同步异常</option></select></label>}</div>{error&&<ErrorState message={error} onRetry={()=>void load()}/>} {loading?<LoadingState/>:tab==="flows"?flows&&flows.records.length?<FundsTable records={flows.records}/>:<EmptyState/>:details&&details.records.length?<DetailsTable records={details.records}/>:<EmptyState/>}{active&&active.total>0&&<Pagination page={active.page} pages={active.pages} total={active.total} onChange={setPage}/>}</>;
}
function FundsTable({records}:{records:FundsFlow[]}){return <div className="table-panel"><div className="table-scroll"><table className="data-table"><thead><tr><th>仓库</th><th>OMS 订单号</th><th>平台订单号</th><th>金额</th><th>业务模块</th><th>费用时间</th><th>明细状态</th></tr></thead><tbody>{records.map(item=><tr key={item.id}><td><strong>{item.wh_code}</strong></td><td>{item.order_no||"-"}</td><td>{item.platform_order_no||"-"}</td><td><strong>{money(item.cost_total,item.currency_code)}</strong></td><td>{item.module_type??"-"}</td><td>{dateTime(item.cost_time)}</td><td><StatusBadge status={item.detail_sync_status}/></td></tr>)}</tbody></table></div></div>}
function DetailsTable({records}:{records:CostDetail[]}){return <div className="table-panel"><div className="table-scroll"><table className="data-table"><thead><tr><th>仓库</th><th>费用单号</th><th>查询订单号</th><th>平台订单号</th><th>费用总额</th><th>费用项目</th><th>创建时间</th></tr></thead><tbody>{records.map(item=><tr key={`${item.wh_code}-${item.cost_no}`}><td><strong>{item.wh_code}</strong></td><td>{item.cost_no}</td><td>{item.query_order_no}</td><td>{item.platform_order_no||"-"}</td><td><strong>{money(item.cost_total,item.currency_code)}</strong></td><td>{item.item_count}</td><td>{dateTime(item.create_time)}</td></tr>)}</tbody></table></div></div>}
