import { Boxes, Check, CircleDollarSign, FileSearch, Play, RefreshCw } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { api } from "../api";
import { EmptyState, ErrorState, LoadingState, PageHeader, StatusBadge, dateTime, number } from "../components/Common";
import type { InventoryKind, SyncRun, Warehouse } from "../types";

const inventoryKinds:{key:InventoryKind;label:string}[]=[{key:"integrated",label:"综合库存"},{key:"stock_age",label:"产品库龄"},{key:"stock_flow",label:"产品流水"},{key:"box_stock",label:"箱库存"},{key:"box_stock_age",label:"箱库龄"},{key:"box_segment_age",label:"分段库龄"},{key:"box_stock_flow",label:"箱库存流水"}];
const targetLabels:Record<string,string>={funds_flow:"资金流水",cost_details:"费用明细",integrated:"综合库存",stock_age:"产品库龄",stock_flow:"产品流水",box_stock:"箱库存",box_stock_age:"箱库龄",box_segment_age:"分段库龄",box_stock_flow:"箱库存流水"};
export default function SyncPage({warehouse,warehouses}:{warehouse:string;warehouses:Warehouse[]}){
  const active=useMemo(()=>warehouses.filter(item=>item.active),[warehouses]);const [selectedWarehouse,setSelectedWarehouse]=useState(warehouse||"");const [target,setTarget]=useState<"inventory"|"funds"|"details">("inventory");const [kinds,setKinds]=useState<InventoryKind[]>(inventoryKinds.map(item=>item.key));const [runs,setRuns]=useState<SyncRun[]>([]);const [loading,setLoading]=useState(true);const [running,setRunning]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");
  useEffect(()=>{if(warehouse)setSelectedWarehouse(warehouse);else if(!selectedWarehouse&&active[0])setSelectedWarehouse(active[0].wh_code);},[warehouse,active]);
  const load=async(silent=false)=>{if(!silent)setLoading(true);try{setRuns(await api.syncRuns());}catch(reason){if(!silent)setError(reason instanceof Error?reason.message:"无法读取同步记录");}finally{if(!silent)setLoading(false);}};
  useEffect(()=>{void load();},[]);useEffect(()=>{if(!runs.some(item=>item.status==="running"))return;const timer=window.setInterval(()=>void load(true),3000);return()=>window.clearInterval(timer);},[runs]);
  const trigger=async()=>{if(!selectedWarehouse)return;setRunning(true);setError("");setMessage("");try{if(target==="inventory")await api.syncInventory(selectedWarehouse,kinds);else if(target==="funds")await api.syncFundsFlow(selectedWarehouse);else await api.syncCostDetails(selectedWarehouse);setMessage("同步任务已提交");await load(true);}catch(reason){setError(reason instanceof Error?reason.message:"提交失败");}finally{setRunning(false);}};
  const toggleKind=(kind:InventoryKind)=>setKinds(current=>current.includes(kind)?current.filter(item=>item!==kind):[...current,kind]);
  return <><PageHeader title="同步中心" subtitle="OpenAPI 数据同步与运行记录" actions={<button className="icon-button bordered" onClick={()=>void load()} title="刷新"><RefreshCw size={18}/></button>}/><section className="sync-console"><div className="sync-targets"><button className={target==="inventory"?"active":""} onClick={()=>setTarget("inventory")}><span><Boxes size={20}/></span><div><strong>库存数据</strong><small>7 个库存接口</small></div></button><button className={target==="funds"?"active":""} onClick={()=>setTarget("funds")}><span><CircleDollarSign size={20}/></span><div><strong>资金流水</strong><small>分页费用流水</small></div></button><button className={target==="details"?"active":""} onClick={()=>setTarget("details")}><span><FileSearch size={20}/></span><div><strong>费用明细</strong><small>待处理订单回填</small></div></button></div><div className="sync-config"><label><span>目标仓库</span><select value={selectedWarehouse} onChange={event=>setSelectedWarehouse(event.target.value)}><option value="">选择仓库</option>{active.map(item=><option value={item.wh_code} key={item.wh_code}>{item.name||item.wh_code} · {item.wh_code}</option>)}</select></label>{target==="inventory"&&<div className="kind-checks">{inventoryKinds.map(item=><label key={item.key}><input type="checkbox" checked={kinds.includes(item.key)} onChange={()=>toggleKind(item.key)}/><span className="check-box">{kinds.includes(item.key)&&<Check size={13}/>}</span><b>{item.label}</b></label>)}</div>}<button className="primary-button wide" disabled={!selectedWarehouse||running||(target==="inventory"&&kinds.length===0)} onClick={()=>void trigger()}><Play size={16}/>{running?"提交中":"开始同步"}</button></div></section>{message&&<div className="success-banner">{message}</div>}{error&&<ErrorState message={error}/>}<div className="section-title"><div><h2>运行记录</h2><p>最近 {runs.length} 次作业</p></div></div>{loading?<LoadingState/>:runs.length?<div className="table-panel"><div className="table-scroll"><table className="data-table"><thead><tr><th>任务</th><th>仓库</th><th>状态</th><th>读取</th><th>写入 / 成功</th><th>失败</th><th>开始时间</th><th>耗时</th></tr></thead><tbody>{runs.map(run=><tr key={run.id}><td><strong>{targetLabels[run.target]||run.target}</strong></td><td>{run.wh_code||"-"}</td><td><StatusBadge status={run.status}/></td><td>{number(run.records_seen||run.targets)}</td><td>{number(run.records_saved||run.succeeded)}</td><td className={run.failed?"danger":""}>{number(run.failed)}</td><td>{dateTime(run.started_at)}</td><td>{duration(run)}</td></tr>)}</tbody></table></div></div>:<EmptyState label="暂无同步记录"/>}</>;
}
function duration(run:SyncRun){if(!run.finished_at)return run.status==="running"?"进行中":"-";const seconds=Math.max(0,Math.round((new Date(run.finished_at).getTime()-new Date(run.started_at).getTime())/1000));return seconds<60?`${seconds} 秒`:`${Math.floor(seconds/60)}分 ${seconds%60}秒`;}
