from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping, MutableMapping, Sequence
from typing import Any
from uuid import UUID

import psycopg
from psycopg.types.json import Jsonb


SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS xlwms_warehouses (
    wh_code text PRIMARY KEY,
    warehouse_name text,
    api_base_url text NOT NULL,
    app_key_ciphertext text NOT NULL,
    app_secret_ciphertext text NOT NULL,
    app_key_hint text NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    disabled_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_xlwms_warehouses_active
    ON xlwms_warehouses (wh_code) WHERE is_active;

CREATE TABLE IF NOT EXISTS xlwms_funds_flows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key text NOT NULL UNIQUE,
    wh_code text NOT NULL REFERENCES xlwms_warehouses(wh_code),
    order_no text,
    platform_order_no text,
    cost_total numeric,
    currency_code text,
    cost_status integer,
    module_type integer,
    cost_time timestamp without time zone,
    bill_status integer,
    relate_bill_no text,
    raw_payload jsonb NOT NULL,
    snapshot_token uuid,
    detail_sync_status text NOT NULL DEFAULT 'pending',
    detail_attempts integer NOT NULL DEFAULT 0,
    detail_last_attempt_at timestamptz,
    detail_error_code text,
    detail_error_message text,
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE xlwms_funds_flows
    ADD COLUMN IF NOT EXISTS snapshot_token uuid,
    ADD COLUMN IF NOT EXISTS detail_sync_status text NOT NULL DEFAULT 'pending',
    ADD COLUMN IF NOT EXISTS detail_attempts integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS detail_last_attempt_at timestamptz,
    ADD COLUMN IF NOT EXISTS detail_error_code text,
    ADD COLUMN IF NOT EXISTS detail_error_message text;

CREATE INDEX IF NOT EXISTS idx_xlwms_funds_flows_order
    ON xlwms_funds_flows (wh_code, order_no);

CREATE INDEX IF NOT EXISTS idx_xlwms_funds_flows_platform_order
    ON xlwms_funds_flows (wh_code, platform_order_no);

CREATE INDEX IF NOT EXISTS idx_xlwms_funds_flows_cost_time
    ON xlwms_funds_flows (wh_code, cost_time DESC);

CREATE INDEX IF NOT EXISTS idx_xlwms_funds_flows_module_status
    ON xlwms_funds_flows (wh_code, module_type, cost_status, bill_status);

CREATE TABLE IF NOT EXISTS xlwms_cost_details (
    wh_code text NOT NULL REFERENCES xlwms_warehouses(wh_code),
    cost_no text NOT NULL,
    query_order_no text NOT NULL,
    query_order_type integer NOT NULL,
    cost_total numeric,
    bill_status integer,
    module_type integer,
    currency_code text,
    cost_status integer,
    create_time timestamp without time zone,
    platform_order_no text,
    relate_bill_no text,
    raw_payload jsonb NOT NULL,
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_fetched_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (wh_code, cost_no),
    CHECK (query_order_type IN (1, 2))
);

CREATE INDEX IF NOT EXISTS idx_xlwms_cost_details_query_order
    ON xlwms_cost_details (wh_code, query_order_no, query_order_type);

CREATE INDEX IF NOT EXISTS idx_xlwms_cost_details_platform_order
    ON xlwms_cost_details (wh_code, platform_order_no);

CREATE TABLE IF NOT EXISTS xlwms_cost_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wh_code text NOT NULL,
    cost_no text NOT NULL,
    item_index integer NOT NULL,
    bill_item_name text,
    bill_item_total numeric,
    charge_time timestamp without time zone,
    raw_payload jsonb NOT NULL,
    FOREIGN KEY (wh_code, cost_no)
        REFERENCES xlwms_cost_details(wh_code, cost_no) ON DELETE CASCADE,
    UNIQUE (wh_code, cost_no, item_index)
);

CREATE INDEX IF NOT EXISTS idx_xlwms_cost_items_name
    ON xlwms_cost_items (wh_code, bill_item_name);
"""


def initialize_schema(database_url: str) -> dict[str, Any]:
    with psycopg.connect(database_url) as conn:
        with conn.cursor() as cur:
            cur.execute(SCHEMA_SQL)
            cur.execute("SELECT current_database(), current_user")
            database, user = cur.fetchone()
            cur.execute(
                """
                SELECT tablename
                FROM pg_tables
                WHERE schemaname = 'public' AND tablename LIKE 'xlwms_%'
                ORDER BY tablename
                """
            )
            tables = [row[0] for row in cur.fetchall()]
    return {"database": database, "user": user, "tables": tables}


def funds_flow_payload_hash(record: Mapping[str, Any]) -> str:
    encoded = json.dumps(
        dict(record),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def funds_flow_source_key(
    warehouse_code: str,
    record: Mapping[str, Any],
    occurrence: int = 1,
) -> str:
    if occurrence < 1:
        raise ValueError("occurrence must be greater than or equal to 1")
    identity = f"{warehouse_code.strip().upper()}:{funds_flow_payload_hash(record)}:{occurrence}"
    return hashlib.sha256(identity.encode("utf-8")).hexdigest()


def upsert_funds_flow_records(
    conn: psycopg.Connection,
    warehouse_code: str,
    records: Sequence[Mapping[str, Any]],
    *,
    occurrence_counts: MutableMapping[str, int] | None = None,
    snapshot_token: UUID | None = None,
) -> int:
    warehouse_code = warehouse_code.strip().upper()
    if occurrence_counts is None:
        occurrence_counts = {}
    values = []
    for record in records:
        returned_wh_code = (record.get("whCode") or warehouse_code).strip().upper()
        if returned_wh_code != warehouse_code:
            raise ValueError(
                f"warehouse response mismatch: expected {warehouse_code}, got {returned_wh_code}"
            )
        payload_hash = funds_flow_payload_hash(record)
        occurrence_counts[payload_hash] = occurrence_counts.get(payload_hash, 0) + 1
        values.append(
            (
                funds_flow_source_key(
                    warehouse_code, record, occurrence_counts[payload_hash]
                ),
                warehouse_code,
                record.get("orderNo"),
                record.get("platformOrderNo"),
                record.get("costTotal"),
                record.get("currencyCode"),
                record.get("costStatus"),
                record.get("moduleType"),
                record.get("costTime") or None,
                record.get("billStatus"),
                record.get("relateBillNo"),
                Jsonb(dict(record)),
                snapshot_token,
            )
        )
    if not values:
        return 0
    with conn.cursor() as cur:
        cur.executemany(
            """
            INSERT INTO xlwms_funds_flows (
                source_key, wh_code, order_no, platform_order_no, cost_total,
                currency_code, cost_status, module_type, cost_time, bill_status,
                relate_bill_no, raw_payload, snapshot_token
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (source_key) DO UPDATE SET
                cost_total = EXCLUDED.cost_total,
                cost_status = EXCLUDED.cost_status,
                bill_status = EXCLUDED.bill_status,
                relate_bill_no = EXCLUDED.relate_bill_no,
                raw_payload = EXCLUDED.raw_payload,
                snapshot_token = EXCLUDED.snapshot_token,
                last_seen_at = now()
            """,
            values,
        )
    return len(values)


def delete_stale_funds_flow_records(
    conn: psycopg.Connection,
    warehouse_code: str,
    snapshot_token: UUID,
) -> int:
    with conn.cursor() as cur:
        cur.execute(
            """
            DELETE FROM xlwms_funds_flows
            WHERE wh_code = %s
              AND snapshot_token IS DISTINCT FROM %s
            """,
            (warehouse_code.strip().upper(), snapshot_token),
        )
        return cur.rowcount


def _optional_int(value: Any) -> int | None:
    if value is None or value == "":
        return None
    return int(value)


def upsert_cost_detail(
    conn: psycopg.Connection,
    warehouse_code: str,
    query_order_no: str,
    query_order_type: int,
    detail: Mapping[str, Any],
) -> tuple[str, int]:
    warehouse_code = warehouse_code.strip().upper()
    cost_no = str(detail.get("costNo") or "").strip()
    if not cost_no:
        raise ValueError("costDetail response is missing costNo")
    items = detail.get("costItemList") or []
    if not isinstance(items, list):
        raise ValueError("costDetail costItemList must be an array")
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO xlwms_cost_details (
                wh_code, cost_no, query_order_no, query_order_type, cost_total,
                bill_status, module_type, currency_code, cost_status, create_time,
                platform_order_no, relate_bill_no, raw_payload
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (wh_code, cost_no) DO UPDATE SET
                query_order_no = EXCLUDED.query_order_no,
                query_order_type = EXCLUDED.query_order_type,
                cost_total = EXCLUDED.cost_total,
                bill_status = EXCLUDED.bill_status,
                module_type = EXCLUDED.module_type,
                currency_code = EXCLUDED.currency_code,
                cost_status = EXCLUDED.cost_status,
                create_time = EXCLUDED.create_time,
                platform_order_no = EXCLUDED.platform_order_no,
                relate_bill_no = EXCLUDED.relate_bill_no,
                raw_payload = EXCLUDED.raw_payload,
                last_fetched_at = now()
            """,
            (
                warehouse_code,
                cost_no,
                query_order_no,
                query_order_type,
                detail.get("costTotal"),
                _optional_int(detail.get("billStatus")),
                _optional_int(detail.get("moduleType")),
                detail.get("currencyCode"),
                _optional_int(detail.get("costStatus")),
                detail.get("createTime") or None,
                detail.get("platformOrderNo"),
                detail.get("relateBillNo"),
                Jsonb(dict(detail)),
            ),
        )
        cur.execute(
            "DELETE FROM xlwms_cost_items WHERE wh_code = %s AND cost_no = %s",
            (warehouse_code, cost_no),
        )
        if items:
            cur.executemany(
                """
                INSERT INTO xlwms_cost_items (
                    wh_code, cost_no, item_index, bill_item_name,
                    bill_item_total, charge_time, raw_payload
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                """,
                [
                    (
                        warehouse_code,
                        cost_no,
                        index,
                        item.get("billItemName"),
                        item.get("billItemTotal"),
                        item.get("chargeTime") or None,
                        Jsonb(dict(item)),
                    )
                    for index, item in enumerate(items)
                ],
            )
    return cost_no, len(items)


def mark_detail_target_status(
    conn: psycopg.Connection,
    warehouse_code: str,
    order_no: str,
    module_type: int | None,
    *,
    status: str,
    attempts: int,
    error_code: str | None = None,
    error_message: str | None = None,
) -> int:
    if status not in {"pending", "success", "error"}:
        raise ValueError(f"invalid detail sync status: {status}")
    with conn.cursor() as cur:
        cur.execute(
            """
            UPDATE xlwms_funds_flows
            SET detail_sync_status = %s,
                detail_attempts = detail_attempts + %s,
                detail_last_attempt_at = now(),
                detail_error_code = %s,
                detail_error_message = %s
            WHERE wh_code = %s
              AND order_no = %s
              AND module_type IS NOT DISTINCT FROM %s
            """,
            (
                status,
                attempts,
                error_code,
                error_message[:1000] if error_message else None,
                warehouse_code.strip().upper(),
                order_no,
                module_type,
            ),
        )
        return cur.rowcount
